# Generated by Django 4.0.3 on 2022-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In-progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=11)),
                ('name', models.TextField()),
            ],
        ),
    ]
